# ─── Configuración general ───
spring.application.name=backend

# ─── Configuración de la base de datos PostgreSQL ───

spring.datasource.url=jdbc:postgresql://localhost:5432/appdb
spring.datasource.username=dev
spring.datasource.password=dev
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ─── SpringDoc / Swagger UI ───
springdoc.swagger-ui.path=/
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.cache.disabled=true
